; Default target configuration file for PlatformIO. It is used to build the project and upload it to the board.
[platformio]
default_envs = nice_nano_v2_debug

; This is a default target configuration file for PlatformIO. It is used to build the project and upload it to the board.
[env:nice_nano_v2]
platform = nordicnrf52
board = nrf52840_dk
framework = zephyr

board_build.zephyr.app_overlay = app.overlay

build_src_flags =
    -Wall
    -Wextra
    ; -DLOW_BATTERY_SHUTDOWN

upload_protocol = custom
extra_scripts = pre:scripts/find_uf2.py
upload_command = "${PYTHONEXE}" "${PROJECT_PACKAGES_DIR}\framework-zephyr\scripts\uf2conv.py" -c -f 0xada52840 -o "${BUILD_DIR}\firmware.uf2" "${BUILD_DIR}\firmware.hex" && copy /Y "${BUILD_DIR}\firmware.uf2" "$UPLOAD_PORT"

[env:nice_nano_v2_debug]
extends = env:nice_nano_v2
build_flags =
    ${env.build_flags}
    -g
board_build.zephyr.cmake_extra_args =
    -DOVERLAY_CONFIG=prj_debug.conf

; This is a second environment for DFU upload, which is slower but more reliable than UF2. It uses the Adafruit nRFUtil tool to perform a DFU upload over serial.
[env:nice_nano_v2_dfu]
platform = nordicnrf52
board = nrf52840_dk
framework = zephyr

board_build.zephyr.app_overlay = app.overlay

build_flags =
    -g

upload_protocol = custom
extra_scripts = pre:scripts/find_port.py
upload_command = adafruit-nrfutil dfu genpkg --application "${SOURCE}" --sd-req 0x00 "${BUILD_DIR}\firmware.zip" && adafruit-nrfutil dfu serial -pkg "${BUILD_DIR}\firmware.zip" -p "$UPLOAD_PORT" -b 115200

[env:nice_nano_v2_dfu_debug]
extends = env:nice_nano_v2_dfu
board_build.zephyr.cmake_extra_args =
    -DOVERLAY_CONFIG=prj_debug.conf
