# GPIO i I2C
CONFIG_GPIO=y
CONFIG_I2C=y

# ADC
CONFIG_ADC=y

# Bluetooth LE - only broadcaster mode, no observer, peripheral or central
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_OBSERVER=n
CONFIG_BT_PERIPHERAL=n
CONFIG_BT_CENTRAL=n
CONFIG_BT_SMP=n
CONFIG_BT_DEVICE_NAME="WeatherStation"
CONFIG_BT_DEVICE_NAME_DYNAMIC=y

# Power Management
CONFIG_PM=y
CONFIG_PM_DEVICE=y

# UART/console - production low-power defaults
CONFIG_STDOUT_CONSOLE=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n

# Disable boot info
CONFIG_BOOT_BANNER=n

# Flash for nRF52840 UF2 bootloader
CONFIG_FLASH_LOAD_OFFSET=0x26000
